###### docker-compose with only external images ######
version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    container_name: "java-gatling-otel-collector"
    command: [ "--config=/etc/opentelemetry/otel-config.yml" ]
    volumes:
      - ./docker-config/opentelemetry/otel-config.yml:/etc/opentelemetry/otel-config.yml
    ports:
      - "4318:4318"   # OTLP HTTP
    env_file:
      - ./env/.env

  influxdb:
    image: influxdb:2.7
    container_name: "gatling-influx"
#    volumes:
#      - ./docker-config/influx/influx-config.yaml:/etc/influxdb2/configs/influx-config.yaml
    ports:
      - "8086:8086"
    env_file:
      - ./env/.env

  grafana:
    image: grafana/grafana:9.5.14
    container_name: "gatling-grafana"
    volumes:
      - ./docker-config/grafana/provisioning:/usr/share/grafana/custom/
      - ./docker-config/grafana/my-dashboards:/usr/share/grafana/public/dashboards
    ports:
      - "3030:3000"
    env_file:
      - ./env/.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
    depends_on:
      - influxdb

  rabbit:
    image: rabbitmq:3-management
    user: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 5s
