version: '3.9'

services:
  gatling-adapter:
    container_name: "java-gatling-adapter"
    build:
      context: gatling-adapter
      dockerfile: Dockerfile
    volumes:
      - ./gatling-runner/src/gatling/resources/config:/app/gatling-adapter/src/main/resources/gatling
    ports:
      - "8090:8090"

  gatling-runner:
    container_name: "java-gatling-runner"
    build:
      context: gatling-runner
      dockerfile: Dockerfile
    volumes:
      - ./gatling-runner/src/gatling/resources/config:/app/gatling-runner/src/gatling/resources/config
    ports:
      - "8091:8091"
    depends_on:
      gatling-adapter:
        condition: service_completed_successfully



#############
#  influxdb:
#    image: influxdb:latest
#    container_name: "gatling-influx"
#    ports:
#      - "8086:8086"
#    env_file:
#      - ./env/.env
#
#  grafana:
#    image: grafana/grafana:9.1.8
#    container_name: "gatling-grafana"
#    volumes:
#      - ./docker-config/grafana/provisioning:/usr/share/grafana/custom/
#      - ./docker-config/grafana/my-dashboards:/usr/share/grafana/public/dashboards
#    ports:
#      - "3030:3000"
#    env_file:
#      - ./env/.env
#    environment:
#      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
#    depends_on:
#      - influxdb

