{
 "title": "Gatling Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"status\"] == \"OK\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.name}))"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.name }))"
    }
   ]
  },
  {
   "title": "Failed Request Counts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_failure_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.name }))"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n    |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.name}))"
    }
   ]
  },
  {
   "title": "Last Simulation Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"request_count\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n|> last()\r\n|> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"All Requests\" }))"
    },
    {
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"request_failure_count\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n|> last()\r\n|> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Failed Requests\" }))"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request_failure_rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Error Rate \" }))"
    }
   ]
  },
  {
   "title": "Total Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total_runtime_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Simulation Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total_runtime_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> count()"
    }
   ]
  }
 ]
}